services:
  overleafserver:
    image: sharelatex/sharelatex:5.2.1
    container_name: overleafserver
    hostname: overleafserver
    restart: always
    volumes:
    expose:
    - 80
    environment:
      GIT_BRIDGE_ENABLED: false
      GIT_BRIDGE_HOST: git-bridge
      GIT_BRIDGE_PORT: 8000
      REDIS_HOST: overleafredis
      REDIS_PORT: 6379
      OVERLEAF_REDIS_HOST: overleafredis
      V1_HISTORY_URL: http://127.0.0.1:3100/api
      OVERLEAF_MONGO_URL: mongodb://overleafmongo/sharelatex
      OVERLEAF_APP_NAME: ${OVERLEAF_APP_NAME}
      ENABLED_LINKED_FILE_TYPES: project_file,project_output_file
      ENABLE_CONVERSIONS: true
      EMAIL_CONFIRMATION_DISABLED: false
      OVERLEAF_BEHIND_PROXY: true
      OVERLEAF_SECURE_COOKIE: true
      OVERLEAF_SITE_URL: ${OVERLEAF_SITE_URL}
      OVERLEAF_NAV_TITLE: ${OVERLEAF_NAV_TITLE}
      OVERLEAF_ADMIN_EMAIL: ${OVERLEAF_ADMIN_EMAIL}
      OVERLEAF_EMAIL_FROM_ADDRESS: ${OVERLEAF_EMAIL_FROM_ADDRESS}
      OVERLEAF_EMAIL_SMTP_HOST: ${OVERLEAF_EMAIL_SMTP_HOST}
      OVERLEAF_EMAIL_SMTP_PORT: ${OVERLEAF_EMAIL_SMTP_PORT}
      OVERLEAF_EMAIL_SMTP_SECURE: ${OVERLEAF_EMAIL_SMTP_SECURE}
      OVERLEAF_EMAIL_SMTP_USER: ${OVERLEAF_EMAIL_SMTP_USER}
      OVERLEAF_EMAIL_SMTP_PASS: ${OVERLEAF_EMAIL_PASSWORD}
      OVERLEAF_EMAIL_SMTP_LOGGER: true
      OVERLEAF_CUSTOM_EMAIL_FOOTER: ${OVERLEAF_CUSTOM_EMAIL_FOOTER}
      OIDC_ISSUER: ${OIDC_ISSUER}
      OIDC_AUTHORIZATION_URL: ${OIDC_AUTHORIZATION_URL}
      OIDC_TOKEN_URL: ${OIDC_TOKEN_URL}
      OIDC_USERINFO_URL: ${OIDC_USERINFO_URL}
      OIDC_CALLBACK_URL: ${OIDC_CALLBACK_URL}
      OIDC_CLIENT_ID: ${OIDC_CLIENT_ID}
      OIDC_CLIENT_SECRET: ${OIDC_CLIENT_SECRET}
      DOCKER_RUNNER: true
      TEXLIVE_IMAGE_USER: www-data
      COMPILES_HOST_DIR: /docker/compose/overleafserver/data/data/compiles
      SANDBOXED_COMPILES: true
      SANDBOXED_COMPILES_SIBLING_CONTAINERS: true
      SANDBOXED_COMPILES_HOST_DIR: /docker/compose/overleafserver/data/data/compiles
      TEXLIVE_IMAGE: texlive/texlive:latest-full
      SYNCTEX_BIN_HOST_PATH: /docker/compose/overleafserver/data/bin/synctex
    entrypoint: |
      /bin/sh -c "cd /var/lib/overleaf && touch prep.sh && sh prep.sh && cd / && /sbin/my_init"
    networks:
    - overleaf-network
volumes:
  overleaf_data:
networks:
  overleaf-network:
    external: true
