volumes:
  - /docker/features/references/5.2.1/overleaf/services/web/config/settings.defaults.js:/overleaf/services/web/config/settings.defaults.js
  - /docker/features/references/5.2.1/overleaf/services/references/package.json:/overleaf/services/references/package.json
  - /docker/features/references/5.2.1/overleaf/services/references/README.md:/overleaf/services/references/README.md
  - /docker/features/references/5.2.1/overleaf/services/references/app.js:/overleaf/services/references/app.js
  - /docker/features/references/5.2.1/overleaf/services/references/app/js/ReferencesAPIController.js:/overleaf/services/references/app/js/ReferencesAPIController.js
  - /docker/features/references/5.2.1/overleaf/services/references/config/settings.defaults.cjs:/overleaf/services/references/config/settings.defaults.cjs
  - /docker/features/references/5.2.1/etc/overleaf/env.sh:/etc/overleaf/env.sh
  - /docker/features/references/5.2.1/etc/service/references-overleaf/run:/etc/service/references-overleaf/run
