services:
  hajtexsshd:
    image: hajtex_sshd_image
    container_name: hajtexsshd
    hostname: hajtexsshd
    restart: always
    volumes:
      - /docker/compose/hajtex_sshd/downloads:/downloads
      - /docker/compose/hajtex_sshd/etc:/etc

      - /docker/compose/hajtex_sshd/hostname:/etc/hostname:ro
      - /docker/compose/hajtex_sshd/hosts:/etc/hosts:ro
      - /docker/compose/hajtex_sshd/resolv.conf:/etc/resolv.conf:ro
      - /docker/compose/hajtex_sshd/sshd_config:/etc/ssh/sshd_config:ro
      - /docker/compose/hajtex_sshd/pam_sshd:/etc/pam.d/sshd:ro
      - /docker/compose/hajtex_sshd/config.toml:/etc/kc-ssh-pam/config.toml:ro
      - /docker/compose/hajtex_sshd/update_userlist.py:/update_userlist.py:ro
      - /docker/compose/hajtex_sshd/list_projects_of_user.py:/list_projects_of_user.py:ro
      - /docker/compose/hajtex_sshd/process_user_login.sh:/process_user_login.sh:ro

    ports:
      - 993:22
    environment:
      PUID: 1000
      PGID: 1000
      TZ: Etc/UTC
    networks:
      - overleaf-network
      - keycloak-network

networks:
  overleaf-network:
    external: true
  keycloak-network:
    external: true

