services:
  hajtexsshd:
    image: hajtex_sshd_image
    container_name: hajtexsshd
    hostname: hajtexsshd
    restart: always
    volumes:
      - /docker/compose/hajtex_sshd/downloads:/downloads
      - /docker/compose/hajtex_sshd/etc:/etc

      - /docker/compose/hajtex_sshd/files/sshd_config:/etc/ssh/sshd_config:ro
      - /docker/compose/hajtex_sshd/files/pam_sshd:/etc/pam.d/sshd:ro
      - /docker/compose/hajtex_sshd/files/update_userlist.py:/update_userlist.py:ro
      - /docker/compose/hajtex_sshd/files/list_projects_of_user.py:/list_projects_of_user.py:ro
      - /docker/compose/hajtex_sshd/files/get_projects.py:/get_projects.py:ro
      - /docker/compose/hajtex_sshd/files/clean_project.py:/clean_project.py:ro

      - /docker/compose/hajtex_sshd/files/process_user_session.sh:/process_user_session.sh:ro
      - /docker/compose/hajtex_sshd/files/process_user_auth.sh:/process_user_auth.sh:ro
      - /docker/compose/hajtex_sshd/files/build_jail.sh:/build_jail.sh:ro

      - /docker/compose/hajtex_sshd/config.toml:/etc/kc-ssh-pam/config.toml:ro
      - /docker/compose/hajtex_sshd/config.json:/config.json:ro



    ports:
      - 993:22
    environment:
      PUID: 1000
      PGID: 1000
      TZ: Etc/UTC
    networks:
      - overleaf-network
      - keycloak-network

networks:
  overleaf-network:
    external: true
  keycloak-network:
    external: true

